### ISSUE TITLE
Reproduce Annotation Projection from Imani et al.

### ISSUE THREAD

**Issue by janetzki** [janetzki/GUIDE#37]
## Goal
I want to project semantic domain questions as labels from `eng` + `fra` to `deu` + `gej` verses for at least 10 verses.

## Tasks
- [x] Align single verses instead of whole corpus
  - [x] Save them as .connl files
- [x] Add all SemDom questions as labels
- [x] Run GNN with this data
- [x] Run on remote server
- [x] Run with 10 verses
- [ ] Run with 4 languages
- [ ] (try out XLM-R / static embeddings)
- [ ] (try out multiple labels per token)

**Comment by janetzki** [comment]
Closed because I cannot debug the code because I do not understand it.
